<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProcessTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            ['title' => 'Overall Risk Profile and Complexity', 'process_id' => 'ARTC-001', 'description' => 'Financial entities must consider their size, risk profile, and operational complexity when developing ICT security policies and frameworks. This includes assessing encryption, network security, project management, and the potential impact of ICT risks on data confidentiality, integrity, availability, and business continuity.'],
            ['title' => 'General Elements of ICT Security Policies, Procedures, Protocols, and Tools', 'process_id' => 'ARTC-002', 'description' => 'ICT security policies must ensure network security, contain safeguards against intrusions and data misuse, and preserve data availability, authenticity, integrity, and confidentiality. Policies should be aligned with information security objectives, approved by management, include monitoring indicators, and address staff responsibilities and compliance consequences.'],
            ['title' => 'ICT Risk Management', 'process_id' => 'ARTC-003', 'description' => 'Financial entities must develop ICT risk management policies documenting approved risk tolerance levels, procedures for risk assessment identifying vulnerabilities and threats, implementation of risk treatment measures, management of residual risks, monitoring of cyber threats, and ensuring business strategy changes are incorporated into risk management processes.'],
            ['title' => 'ICT Asset Management Policy', 'process_id' => 'ARTC-004', 'description' => 'A comprehensive policy prescribing management of ICT asset lifecycles, including monitoring, classification, and record-keeping of all assets with unique identifiers, locations, classifications, owners, supported business functions, business continuity requirements, external network exposure, and interdependencies among systems.'],
            ['title' => 'ICT Asset Management Procedure', 'process_id' => 'ARTC-005', 'description' => 'Procedures must establish criteria for criticality assessment of information and ICT assets supporting business functions. Assessment shall consider ICT risk related to business functions, dependencies, and potential impact of losing confidentiality, integrity, and availability of assets on business processes and activities.'],
            ['title' => 'Encryption and Cryptographic Controls', 'process_id' => 'ARTC-006', 'description' => 'Entities must develop encryption policies based on data classification and ICT risk assessment, covering encryption of data at rest, in transit, and in use. Policies should specify cryptographic technique selection criteria, provisions for updating cryptographic technology, and mitigation measures for non-compliance with leading practices and standards.'],
            ['title' => 'Cryptographic Key Management', 'process_id' => 'ARTC-007', 'description' => 'Financial entities must manage cryptographic keys throughout their lifecycle, implementing controls to protect keys against loss, unauthorized access, disclosure, and modification. Requirements include methods to replace compromised keys, maintaining registers for certificates and certificate-storing devices, and ensuring prompt certificate renewal before expiration.'],
            ['title' => 'Policies and Procedures for ICT Operations', 'process_id' => 'ARTC-008', 'description' => 'Entities must implement comprehensive ICT operations policies and procedures detailing secure installation, maintenance, configuration, deinstallation, controls, monitoring, backup and restore requirements, scheduling, audit-trail protocols, error handling procedures, and environment separation between production and non-production systems.'],
            ['title' => 'Capacity and Performance Management', 'process_id' => 'ARTC-009', 'description' => 'Financial entities must develop capacity and performance management procedures identifying capacity requirements, applying resource optimization, and monitoring procedures for maintaining and improving data and ICT system availability, efficiency, and preventing capacity shortages, with special considerations for complex or resource-intensive systems.'],
            ['title' => 'Vulnerability and Patch Management', 'process_id' => 'ARTC-010', 'description' => 'Entities must identify vulnerabilities through automated scanning, verify third-party service providers handle vulnerabilities and report critical ones, track third-party and open-source libraries, establish responsible disclosure procedures, prioritize patch deployment based on criticality, and monitor remediation of identified vulnerabilities affecting ICT systems.'],
            ['title' => 'Data and System Security', 'process_id' => 'ARTC-011', 'description' => 'A comprehensive data and system security procedure must include access restrictions, secure configuration baselines, authorized software installation measures, malicious code protection, authorized data storage media identification, portable and private endpoint device requirements, secure data deletion and decommission processes, and teleworking security measures.'],
            ['title' => 'Logging', 'process_id' => 'ARTC-012', 'description' => 'Financial entities must develop logging procedures identifying events to be logged, retention periods, measures to secure log data, and level of detail aligned with purpose. Logging must cover logical and physical access control, capacity management, change management, ICT operations, network traffic, with protections against tampering and unauthorized access.'],
            ['title' => 'Network Security Management', 'process_id' => 'ARTC-013', 'description' => 'Network security policies must include ICT system and network segregation based on criticality, documentation of network connections and data flows, separate administration networks, network access controls, encryption of network connections, network design aligning with security requirements, and secure network architecture reviews, firewall rules, and inactivity session termination procedures.'],
            ['title' => 'Securing Information in Transit', 'process_id' => 'ARTC-014', 'description' => 'Entities must develop policies to protect information in transit ensuring data availability, authenticity, integrity, and confidentiality during network transmission. Policies should prevent and detect data leakages, secure information transfer between financial entities and external parties, and implement documented confidentiality or non-disclosure arrangements regularly reviewed.'],
            ['title' => 'ICT Project Management', 'process_id' => 'ARTC-015', 'description' => 'An ICT project management policy must specify project objectives, governance, roles and responsibilities, planning, timeframes, risk assessment, milestones, and change management requirements. It should ensure secure implementation, provide necessary business expertise, and require reporting of critical projects to management body individually or in aggregation.'],
            ['title' => 'ICT Systems Acquisition, Development, and Maintenance', 'process_id' => 'ARTC-016', 'description' => 'A policy governing acquisition, development, and maintenance must identify security practices, technical specifications, acquisition requirements, approval processes, and measures to mitigate unintentional alteration or intentional manipulation. Procedures must ensure testing and approval of systems before use, source code reviews, security testing, and protection of source code integrity.'],
            ['title' => 'ICT Change Management', 'process_id' => 'ARTC-017', 'description' => 'ICT change management procedures must include verification of ICT security requirements, mechanisms ensuring independence of approval and implementation functions, clear roles and responsibilities, documentation and communication of changes, fall-back procedures, emergency change management with adequate safeguards, and assessment of potential impacts on existing security measures.'],
            ['title' => 'Physical and Environmental Security', 'process_id' => 'ARTC-018', 'description' => 'A physical and environmental security policy must protect premises and data centres from attacks, accidents, and environmental threats. Measures must secure ICT assets, ensure availability and integrity through maintenance, preserve data confidentiality with clear desk and screen policies, with protection commensurate to premises importance and operational criticality.'],
            ['title' => 'Human Resources Policy', 'process_id' => 'ARTC-019', 'description' => 'ICT security-related human resource policies must identify ICT security responsibilities and requirements for staff and ICT service provider personnel to be informed about policies, be aware of reporting channels for anomalous behavior including whistleblower channels, and to return ICT and information assets upon termination of employment.'],
            ['title' => 'Identity Management', 'process_id' => 'ARTC-020', 'description' => 'Entities must develop identity management policies ensuring unique identification and authentication of natural persons and systems. Policies must assign unique identities and accounts to staff, implement lifecycle management processes for account creation, change, review, update, temporary deactivation, and termination with automated solutions where feasible.'],
            ['title' => 'Access Control', 'process_id' => 'ARTC-021', 'description' => 'Access control policies must assign access rights based on need-to-know and least privilege principles, implement duty segregation, ensure user accountability, restrict unauthorized access, establish account management procedures, implement authentication methods commensurate to asset classification, and ensure physical access controls with identification and logging of authorized persons.'],
            ['title' => 'ICT-related Incident Management Policy', 'process_id' => 'ARTC-022', 'description' => 'Financial entities must develop ICT-related incident policies documenting the incident management process, establishing relevant contact lists with internal and external stakeholders, implementing technical mechanisms for incident detection and anomaly analysis, retaining incident evidence appropriately, and analyzing significant or recurring incidents and patterns in incident occurrence.'],
            ['title' => 'Anomalous Activities Detection and Criteria for ICT-related Incidents Detection and Response', 'process_id' => 'ARTC-023', 'description' => 'Entities must establish clear roles and responsibilities for detecting and responding to incidents and anomalies. Mechanisms must collect and monitor logs, potential cyber threats, third-party incident notifications, identify anomalies, generate alerts for critical assets, prioritize alerts for resolution, and record comprehensive information on detected anomalies.'],
            ['title' => 'Components of the ICT Business Continuity Policy', 'process_id' => 'ARTC-024', 'description' => 'The ICT business continuity policy must describe objectives, scope, timeframe, governance, organization, roles, responsibilities, escalation procedures, alignment between ICT and business continuity plans, development of recovery plans using risk-based approach, and regular reviews. It must address potential failure scenarios, recovery objectives, and communication strategy alignment.'],
            ['title' => 'Testing of the ICT Business Continuity Plans', 'process_id' => 'ARTC-025', 'description' => 'Financial entities must test business continuity plans based on business impact analysis and ICT risk assessment using scenarios simulating potential disruptions. Testing must assess continuity of critical and important functions, include third-party ICT service scenarios, verify switchover capabilities, challenge underlying assumptions, and verify staff and systems ability to respond adequately.'],
            ['title' => 'ICT Response and Recovery Plans', 'process_id' => 'ARTC-026', 'description' => 'Response and recovery plans must be developed taking into account business impact analysis, specifying activation conditions, actions ensuring availability and recovery of critical systems, meeting recovery objectives, being documented and accessible, providing short and long-term recovery options, and laying down plan objectives and success conditions.'],
            ['title' => 'Format and Content of the Report on the Review of the ICT Risk Management Framework', 'process_id' => 'ARTC-027', 'description' => 'Reports must be submitted in searchable electronic format containing introductory sections identifying the entity and context, management body approval date, reasons for review, start and end dates, responsible function, summary of findings, descriptions of corrective measures with implementation dates, and conclusions on the ICT risk management framework review.'],
            ['title' => 'Governance and Organisation', 'process_id' => 'ARTC-028', 'description' => 'Simplified framework requires governance and control framework ensuring effective ICT risk management. Management body must bear overall responsibility for the framework, set clear roles and responsibilities, approve information security objectives, periodically review classification and policies, allocate necessary budget, and ensure staff have sufficient knowledge and skills to understand ICT risk.'],
            ['title' => 'Information Security Policy and Measures', 'process_id' => 'ARTC-029', 'description' => 'Entities must develop an information security policy in the simplified framework context, specifying high-level principles and rules to protect confidentiality, integrity, availability, and authenticity of data and services. Based on this policy, entities must establish and implement ICT security measures to mitigate exposure to ICT risk.'],
            ['title' => 'Classification of Information Assets and ICT Assets', 'process_id' => 'ARTC-030', 'description' => 'As part of the simplified framework, financial entities must identify, classify, and document all critical and important functions, information assets and ICT assets supporting them, and their interdependencies. Entities must review identification and classification as needed and identify all critical functions supported by ICT third-party service providers.'],
            ['title' => 'ICT Risk Management', 'process_id' => 'ARTC-031', 'description' => 'The simplified framework must include determination of ICT risk tolerance levels, identification and assessment of ICT risks, specification of mitigation strategies, monitoring of effectiveness, and identification and assessment of risks from major changes. Entities must conduct periodic ICT risk assessments commensurate to their risk profile and continuously monitor threats and vulnerabilities.'],
            ['title' => 'Physical and Environmental Security', 'process_id' => 'ARTC-032', 'description' => 'Financial entities must identify and implement physical security measures based on threat landscape and asset classification. Measures must protect premises and data centres from unauthorized access, attacks, accidents, and environmental threats and hazards, with protection commensurate to premises importance and operational criticality of located ICT systems.'],
            ['title' => 'Access Control', 'process_id' => 'ARTC-033', 'description' => 'Entities must develop, document, and implement access control procedures for logical and physical access. Procedures must manage access rights on need-to-know and least privilege basis, ensure user accountability, establish account management procedures, implement strong authentication methods for remote and privileged access, and periodically review and withdraw unnecessary access rights.'],
            ['title' => 'ICT Operations Security', 'process_id' => 'ARTC-034', 'description' => 'Financial entities must monitor and manage ICT asset lifecycles, identify capacity requirements, perform automated vulnerability scanning and assessments, deploy patches to address vulnerabilities, manage risks related to outdated systems, log access control and operations events, monitor anomalous activities, and monitor cyber threats and security vulnerabilities.'],
            ['title' => 'Data, System and Network Security', 'process_id' => 'ARTC-035', 'description' => 'Entities must develop safeguards ensuring network security against intrusions and preserving data availability, authenticity, integrity, and confidentiality. Measures must protect data in use, in transit, and at rest, secure data storage media and systems, prevent unauthorized network connections, ensure network transmission security, and securely delete or decommission data storage devices.'],
            ['title' => 'ICT Security Testing', 'process_id' => 'ARTC-036', 'description' => 'Financial entities must establish an ICT security testing plan validating effectiveness of security measures. The plan must consider identified threats and vulnerabilities, review and assess security measures commensurate to asset risk profile, and monitor and evaluate security testing results, updating measures accordingly without undue delay for critical and important function systems.'],
            ['title' => 'ICT Systems Acquisition, Development, and Maintenance', 'process_id' => 'ARTC-037', 'description' => 'A risk-based acquisition, development, and maintenance procedure must ensure functional and non-functional requirements including security requirements are clearly specified and approved before acquisition or development. Procedures must test and approve systems before first use and before changes to production environment, and mitigate risks of system alteration or manipulation.'],
            ['title' => 'ICT Project and Change Management', 'process_id' => 'ARTC-038', 'description' => 'Entities must develop ICT project management procedures specifying roles and responsibilities covering all project stages from initiation to closure. Change management procedures must ensure all changes to ICT systems are recorded, tested, assessed, approved, implemented, and verified in a controlled manner with adequate safeguards for digital operational resilience.'],
            ['title' => 'Components of the ICT Business Continuity Plan', 'process_id' => 'ARTC-039', 'description' => 'Business continuity plans must be approved by management body, documented and accessible in emergencies, allocate sufficient resources, establish recovery levels and timeframes, identify activation conditions and recovery actions, specify restoration and recovery measures for critical functions, identify backup procedures with required frequencies, and update according to lessons learned.'],
            ['title' => 'Testing of Business Continuity Plans', 'process_id' => 'ARTC-040', 'description' => 'Financial entities must test business continuity plans at least annually for backup and restore procedures or upon major changes. Testing must demonstrate ability to sustain business viability until critical operations are re-established. Results must be documented and any identified deficiencies must be analyzed, addressed, and reported to management body.'],
            ['title' => 'Format and Content of the Report on the Review of the Simplified ICT Risk Management Framework', 'process_id' => 'ARTC-041', 'description' => 'Reports must be submitted in searchable electronic format containing introductory sections with context and context summary, management body approval date where applicable, review reasons including supervisory instructions or incidents, review period dates, responsible person, findings summary and severity assessment, remedying measures and implementation dates, and overall conclusions.'],
            ['title' => 'Entry Into Force', 'process_id' => 'ARTC-042', 'description' => 'The Digital Operational Resilience Act (DORA) Regulation entered into force on the twentieth day following its publication in the Official Journal of the European Union. This Regulation is binding in its entirety and directly applicable in all European Union Member States.'],
        ];

        foreach ($articles as $article) {
            \App\Models\Process::create([
                'title' => $article['title'],
                'slug' => \Illuminate\Support\Str::slug($article['title']),
                'process_id' => $article['process_id'],
                'description' => $article['description'],
            ]);
        }
    }
}
